### ISSUE TITLE
We need help with Travis CI 

### ISSUE THREAD

**Issue by jeremydanner** [schiedel-sweden/Mobile-Application#24]
We need help with Travis CI  that works. Problem: `ERROR: An error occured while trying to parse your .travis.yml file. Please make sure that the file is valid YAML.`

**Comment by kevinah95** [comment]
Can I take this?

**Comment by jeremydanner** [comment]
Yes dud! thank you.

**Comment by jeremydanner** [comment]
Thank you for the help @kevinah95 !

**Comment by kevinah95** [comment]
Sorry bro I made a new commit to fix test task error "node node_modules/jest/bin/jest.js --watch". The issue is related to this issue [Don't force "--watch" into Jest](https://github.com/facebookincubator/create-react-app/issues/784)
