### ISSUE TITLE
About us page

### ISSUE THREAD

**Issue by jeremydanner** [schiedel-sweden/Mobile-Application#25]
We would like some help with the `about us` page. The page can have any [ipsum](http://batman-ipsum.com/) text and any image in the background. [Use this as a reference](https://cdn.cp.adobe.io/content/2/dcx/d734dcec-6d1f-4f4f-88f7-4525c27b572c/content/artwork/artboard-3aefd501-df27-460e-838b-8f67adda63d1/graphicContent.png/version/8). The component to edit is `/src/views/AboutUs/AboutUs.js`. 
Colors to use: `#EEEEEE`, `#B9B9B9`, `#333333`, `#F9CE3C` and `#949494`

**Comment by mdew192837** [comment]
Can you give me some guidance on using React Native? @jeremydanner

**Comment by jeremydanner** [comment]
Please follow are [guidelines](https://github.com/schiedel-sweden/Mobile-Application/blob/master/CONTRIBUTING.md) and the basic [style documentation for react native](https://facebook.github.io/react-native/docs/style.html) @mdew192837

**Comment by brittanyz** [comment]
after cloning, I ran npm install and npm start and it still wont open.. anything I may be missing??

**Comment by brittanyz** [comment]
seems to be a problem with watchman?

**Comment by spencewine** [comment]
I've cloned and it's working for me.  @brittanyz are you tackling this? If not, let me know and I can make the page .

**Comment by jeremydanner** [comment]
``` 
# Remove any existing binaries
rm -rf /usr/local/var/run/watchman/
# Remove any npm globally installed instances
npm uninstall watchman
# Nuke the last brew installed version
brew uninstall watchman
# Brew install and build latest
brew install watchman
```
This should help you @brittanyz

**Comment by Harkindey** [comment]
@jeremydanner working on this already.

**Comment by jeremydanner** [comment]
Nice! @Harkindey

**Comment by Harkindey** [comment]
@jeremydanner please check the Build error for my PR, seems you need to upgrade the node of the Build OS to be able to install node modules with yarn or change Your build script to `npm install`.
Also Your test script Fails.

**Comment by jeremydanner** [comment]
Thanks! We are aware of this. We have just implemented TRAVIS-CI in are application and are still working on it to work  in the right way! Thank you for your work @Harkindey
